-- 07a_query.sql

DELETE FROM CAMION;
DELETE FROM CARBURANT;
DELETE FROM CHARGEMENT;
DELETE FROM CLIENT;
DELETE FROM COMMANDED;
DELETE FROM COMMANDEE;
DELETE FROM COMPAGNIE;
DELETE FROM EQUIPEMENT;
DELETE FROM POSITION;
DELETE FROM ROUTE;
DELETE FROM SOUMISSIOND;
DELETE FROM SOUMISSIONE;
DELETE FROM TRACTEUR;
DELETE FROM TYPEEQUIPEMENT;
COMMIT;
/